const state={stars:0,xp:0,level:1,attempts:0,correct:0,hints:0,round:0,current:null,missionStars:0,treasures:0,mode:'ask'};
const $=id=>document.getElementById(id),MISSION_TARGET=20;
const SUKI_BASE='public/assets/suki/';
const sukiImages={greet:'suki_01_greet.png',happy:'suki_02_happy.png',correct:'suki_03_correct.png',cheer:'suki_04_cheer.png',think:'suki_05_think.png',curious:'suki_06_curious.png',surprise:'suki_07_surprise.png',jump:'avatar_08_jump.png',hint:'suki_09_hint.png',explore:'suki_10_explore.png',rest:'suki_11_rest.png',complete:'suki_12_complete.png'};
const speeches={start:["좋아! 이번엔 내가 문제 낼게!","별을 같이 모아보자!","이번 문제를 해결하면 별을 얻어!"],correct:["찾았다! 너 빠른데?","오! 그 방법 좋다!","우리 별을 얻었어!"],retry:["어? 우리 답이 다른 것 같은데? 같이 확인해보자!","거의 다 왔어. 한 번만 더 생각해볼까?"],hint:["두 무리를 하나로 합쳐서 세어보자!","작은 수부터 손가락으로 더해봐도 좋아!"]};
function pick(a){return a[Math.floor(Math.random()*a.length)]}function save(){localStorage.setItem('mathPlayState',JSON.stringify(state))}function restore(){try{Object.assign(state,JSON.parse(localStorage.getItem('mathPlayState'))||{})}catch{}}
function setSuki(expression='greet'){const img=$('sukiImage'),fallback=$('sukiFallback'),file=sukiImages[expression]||sukiImages.greet;img.onload=()=>{img.hidden=false;fallback.hidden=true};img.onerror=()=>{img.hidden=true;fallback.hidden=false};img.src=SUKI_BASE+file}
function avatarMood(mood='idle',expression){const avatar=$('mascot');avatar.classList.remove('is-happy','is-thinking','is-hint');if(mood==='happy')avatar.classList.add('is-happy');if(mood==='thinking')avatar.classList.add('is-thinking');if(mood==='hint')avatar.classList.add('is-hint');setSuki(expression||(mood==='happy'?'happy':mood==='thinking'?'think':mood==='hint'?'hint':'greet'))}
function updateHud(){$('stars').textContent=state.stars;$('level').textContent=`Lv.${state.level}`;$('xpBar').style.width=`${state.xp%100}%`;$('missionStars').textContent=Math.min(state.missionStars,MISSION_TARGET);$('missionBar').style.width=`${Math.min(100,state.missionStars/MISSION_TARGET*100)}%`;$('treasureBtn').classList.toggle('hidden',state.missionStars<MISSION_TARGET);$('attempts').textContent=state.attempts;$('correct').textContent=state.correct;$('hints').textContent=state.hints;const rate=state.attempts?Math.round(state.correct/state.attempts*100):0;$('parentSummary').textContent=state.attempts?`오늘 ${state.attempts}번 도전, ${state.correct}번 해결했어요. 성공률 ${rate}%, 보물상자 ${state.treasures}개를 열었습니다.`:'아직 오늘의 놀이를 시작하지 않았어요.';save()}
function choicesFor(answer){const s=new Set([answer]);while(s.size<4)s.add(Math.max(1,Math.min(10,answer-2+Math.floor(Math.random()*5))));return [...s].sort(()=>Math.random()-.5)}
function makeProblem(){let a=1+Math.floor(Math.random()*6),b=1+Math.floor(Math.random()*(10-a)),answer=a+b;state.round++;state.mode=state.round%4===0?'teach':'ask';state.current={a,b,answer};$('answers').innerHTML='';$('startBtn').classList.add('hidden');$('hintBtn').classList.remove('hidden');
 if(state.mode==='teach'){let sukiAnswer=answer+(Math.random()<.5?-1:1);avatarMood('thinking','curious');$('mode').textContent='수키를 가르쳐줘!';$('speech').textContent=`내가 ${a}+${b}=${sukiAnswer}라고 했는데… 맞아?`;$('visual').textContent='🤔 수키의 답을 검사해줘';$('question').textContent=`${a} + ${b} = ${sukiAnswer}`;[['맞아',false],['아니야!',true]].forEach(([t,v])=>{const btn=document.createElement('button');btn.className='answer';btn.textContent=t;btn.onclick=()=>teachAnswer(v);$('answers').appendChild(btn)})
 }else{avatarMood('idle','greet');$('mode').textContent='수키가 문제내기';$('speech').textContent=pick(speeches.start);$('visual').textContent='⭐'.repeat(a)+'  +  '+'⭐'.repeat(b);$('question').textContent=`${a} + ${b} = ?`;choicesFor(answer).forEach(n=>{const btn=document.createElement('button');btn.className='answer';btn.textContent=n;btn.onclick=()=>answerProblem(n);$('answers').appendChild(btn)})}}
function reward(extra=0){const bonus=(state.hints===0?3:2)+extra;state.stars+=bonus;state.missionStars+=bonus;state.xp+=15+extra*5;let leveled=false;while(state.xp>=100){state.xp-=100;state.level++;leveled=true}avatarMood('happy',leveled?'jump':'correct');return{bonus,leveled}}
function finishSuccess(message,extra=0){state.correct++;const r=reward(extra);$('speech').textContent=r.leveled?`레벨 업! Lv.${state.level}! 🎉`:`${message} ⭐ +${r.bonus}`;$('visual').textContent=r.leveled?'🚀 ⭐ LEVEL UP ⭐ 🚀':'🎉 ⭐ 🎉';$('answers').innerHTML='';$('hintBtn').classList.add('hidden');$('startBtn').textContent='다음 놀이!';$('startBtn').classList.remove('hidden');updateHud()}
function answerProblem(n){state.attempts++;if(n===state.current.answer){$('question').textContent=`${state.current.a} + ${state.current.b} = ${n}`;finishSuccess(pick(speeches.correct))}else{avatarMood('thinking','think');$('speech').textContent=pick(speeches.retry);updateHud()}}
function teachAnswer(saysWrong){state.attempts++;if(saysWrong){avatarMood('happy','cheer');$('question').textContent=`정답은 ${state.current.answer}!`;finishSuccess('맞아! 네가 나를 가르쳐줬어!',1)}else{avatarMood('thinking','surprise');$('speech').textContent='앗, 다시 계산해볼까? 내가 일부러 실수했을지도 몰라!';updateHud()}}
$('hintBtn').onclick=()=>{state.hints++;avatarMood('hint','hint');$('speech').textContent=pick(speeches.hint);$('visual').textContent=`${'🔵'.repeat(state.current.a)}  ${'🟡'.repeat(state.current.b)}`;updateHud()};
$('treasureBtn').onclick=()=>{if(state.missionStars<MISSION_TARGET)return;state.missionStars-=MISSION_TARGET;state.treasures++;state.stars+=5;state.xp+=20;avatarMood('happy','complete');$('speech').textContent='보물상자 오픈! 보너스 별 5개를 찾았어!';$('visual').textContent='🎁✨ ⭐⭐⭐⭐⭐ ✨🎁';$('question').textContent='오늘의 별 미션 성공!';$('answers').innerHTML='';$('hintBtn').classList.add('hidden');$('startBtn').textContent='계속 모험하기';$('startBtn').classList.remove('hidden');updateHud()};
$('startBtn').onclick=makeProblem;$('parentBtn').onclick=()=>{$('game').classList.add('hidden');$('parentPanel').classList.remove('hidden');updateHud()};$('backBtn').onclick=()=>{$('parentPanel').classList.add('hidden');$('game').classList.remove('hidden');avatarMood('idle','greet')};restore();updateHud();avatarMood('idle','greet');