const defaultState={stars:0,xp:0,level:1,attempts:0,correct:0,hints:0,current:null,missionStars:0,treasures:0,gameType:'duel',gameRound:0,currentWorld:'g1-number',mastery:{}};
const state={...defaultState},$=id=>document.getElementById(id),MISSION_TARGET=20,SUKI_BASE='public/assets/suki/';
let content={worlds:[],modes:[],mastery:null};
const sukiImages={greet:'suki_01_greet.png',happy:'suki_02_happy.png',correct:'suki_03_correct.png',cheer:'suki_04_cheer.png',think:'suki_05_think.png',curious:'suki_06_curious.png',surprise:'suki_07_surprise.png',jump:'avatar_08_jump.png',hint:'suki_09_hint.png',explore:'suki_10_explore.png',rest:'suki_11_rest.png',complete:'suki_12_complete.png'};
const fallbackModes=['duel','star-catch','missing','teach-suki'];
async function loadContent(){try{const [w,g,m]=await Promise.all([fetch('src/data/worlds.json').then(r=>r.json()),fetch('src/data/game-modes.json').then(r=>r.json()),fetch('src/data/mastery.json').then(r=>r.json())]);content.worlds=w.worlds;content.modes=g.modes;content.mastery=m}catch(e){console.warn('Content data load failed',e);content.worlds=[{id:'g1-add',order:1,name:'덧셈숲',icon:'🌳',concepts:['add-10'],stages:['수키와 대결','별잡기','빈칸 찾기','수키 가르치기','최종미션']}];content.modes=fallbackModes.map((id,i)=>({id,name:['수키와 대결','별잡기','빈칸 찾기','수키 가르치기'][i]}))}}
function save(){localStorage.setItem('mathPlayStateV2',JSON.stringify(state))}function restore(){try{Object.assign(state,JSON.parse(localStorage.getItem('mathPlayStateV2'))||{})}catch{}}
function setSuki(x='greet'){const i=$('sukiImage'),f=$('sukiFallback');i.onload=()=>{i.hidden=false;f.hidden=true};i.onerror=()=>{i.hidden=true;f.hidden=false};i.src=SUKI_BASE+(sukiImages[x]||sukiImages.greet)}
function mood(m='idle',x='greet'){const a=$('mascot');a.classList.remove('is-happy','is-thinking','is-hint');if(m==='happy')a.classList.add('is-happy');if(m==='thinking')a.classList.add('is-thinking');if(m==='hint')a.classList.add('is-hint');setSuki(x)}
function world(){return content.worlds.find(w=>w.id===state.currentWorld)||content.worlds[0]}function masteryKey(){return `${state.currentWorld}:${state.gameType}`}function mastery(){return state.mastery[masteryKey()]??50}
function updateMastery(ok,hinted=false){const k=masteryKey(),v=state.mastery[k]??50;state.mastery[k]=Math.max(0,Math.min(100,v+(ok?(hinted?3:5):-2)))}
function updateHud(){$('stars').textContent=state.stars;$('level').textContent=`Lv.${state.level}`;$('xpBar').style.width=`${state.xp%100}%`;$('missionStars').textContent=Math.min(state.missionStars,MISSION_TARGET);$('missionBar').style.width=`${Math.min(100,state.missionStars/MISSION_TARGET*100)}%`;$('treasureBtn').classList.toggle('hidden',state.missionStars<MISSION_TARGET);$('attempts').textContent=state.attempts;$('correct').textContent=state.correct;$('hints').textContent=state.hints;const r=state.attempts?Math.round(state.correct/state.attempts*100):0;$('parentSummary').textContent=`오늘 ${state.attempts}번 도전, ${state.correct}번 해결했어요. 성공률 ${r}%. 현재 활동 숙련도 ${mastery()}%. 보물상자 ${state.treasures}개.`;save()}
function isWorldUnlocked(w){if(w.order===1)return true;const prev=content.worlds.find(x=>x.order===w.order-1);if(!prev)return false;const vals=Object.entries(state.mastery).filter(([k])=>k.startsWith(prev.id+':')).map(([,v])=>v);return vals.length>0&&vals.reduce((a,b)=>a+b,0)/vals.length>=70}
function renderWorld(){const w=world();$('worldNumber').textContent=`WORLD ${w.order}`;$('worldTitle').textContent=`${w.icon} ${w.name}`;$('worldCopy').textContent='수키와 놀이하며 이 월드의 수학을 발견해보자!';$('worldTabs').innerHTML='';content.worlds.forEach(x=>{const b=document.createElement('button');b.className='world-tab'+(x.id===w.id?' active':'');b.textContent=isWorldUnlocked(x)?`${x.icon}${x.order}`:`🔒${x.order}`;b.disabled=!isWorldUnlocked(x);b.onclick=()=>{state.currentWorld=x.id;renderWorld();save()};$('worldTabs').appendChild(b)});$('stageMap').innerHTML='';w.stages.forEach((name,i)=>{const b=document.createElement('button'),mode=content.modes[i%Math.max(1,content.modes.length)]?.id||fallbackModes[i%4];b.className='stage unlocked';b.dataset.game=mode;b.innerHTML=`<b>${i+1}</b><span>${name}</span><small>${i===w.stages.length-1?'월드 최종미션':`숙련도 ${state.mastery[`${w.id}:${mode}`]??50}%`}</small>`;b.onclick=()=>openGame(mode);$('stageMap').appendChild(b)})}
function problem(){const w=world(),sub=w.id.includes('sub');let a=1+Math.floor(Math.random()*9),b=1+Math.floor(Math.random()*Math.max(1,sub?a:10-a));if(sub&&b>a)[a,b]=[b,a];return{a,b,op:sub?'-':'+',answer:sub?a-b:a+b}}
function choices(ans){const s=new Set([ans]);while(s.size<4)s.add(Math.max(0,Math.min(20,ans-2+Math.floor(Math.random()*5))));return[...s].sort(()=>Math.random()-.5)}function buttons(items,fn){$('answers').innerHTML='';items.forEach(v=>{const b=document.createElement('button');b.className='answer';b.textContent=v;b.onclick=()=>fn(v);$('answers').appendChild(b)})}
function modeName(id){return content.modes.find(x=>x.id===id)?.name||id}function openGame(type){state.gameType=type;state.gameRound=0;$('world').classList.add('hidden');$('parentPanel').classList.add('hidden');$('game').classList.remove('hidden');$('mode').textContent=modeName(type);$('speech').textContent='수키와 시작해볼까?';$('visual').textContent='✨';$('question').textContent='';$('answers').innerHTML='';$('startBtn').dataset.action='';$('startBtn').textContent='게임 시작!';$('startBtn').classList.remove('hidden');$('hintBtn').classList.add('hidden');mood('idle','explore');updateHud()}
function next(){state.current=problem();state.gameRound++;const p=state.current,m=state.gameType;$('startBtn').classList.add('hidden');$('hintBtn').classList.remove('hidden');$('mode').textContent=modeName(m);if(m==='teach-suki'){const wrong=p.answer+(Math.random()<.5?-1:1);$('speech').textContent='수키의 계산을 검사해줘!';$('visual').textContent='🤔';$('question').textContent=`${p.a} ${p.op} ${p.b} = ${wrong}`;buttons(['맞아','아니야!'],v=>check(v==='아니야!'));mood('thinking','curious')}else if(m==='missing'){$('speech').textContent='사라진 숫자를 찾아줘!';$('visual').textContent='🔎✨';$('question').textContent=p.op==='+'?`${p.a} + □ = ${p.answer}`:`${p.a} - □ = ${p.answer}`;buttons(choices(p.b),v=>check(v===p.b));mood('idle','curious')}else{$('speech').textContent=m==='star-catch'?`별잡기 ${state.gameRound}/5`:'수키보다 먼저 정답을 찾아!';$('visual').textContent=m==='star-catch'?'⭐💨':'⚡ VS ⚡';$('question').textContent=`${p.a} ${p.op} ${p.b} = ?`;buttons(choices(p.answer),v=>check(v===p.answer));mood('idle',m==='star-catch'?'explore':'greet')}}
function gain(extra=0){const bonus=(state.hints?2:3)+extra;state.stars+=bonus;state.missionStars+=bonus;state.xp+=15+extra*5;let up=false;while(state.xp>=100){state.xp-=100;state.level++;up=true}return{bonus,up}}
function check(ok){state.attempts++;updateMastery(ok,state.hints>0);if(!ok){$('speech').textContent='괜찮아, 다른 방법으로 한번 볼까?';mood('thinking','think');updateHud();return}state.correct++;const r=gain(state.gameType==='teach-suki'?1:0);mood('happy',r.up?'jump':state.gameType==='teach-suki'?'cheer':'correct');$('speech').textContent=r.up?`레벨 업! Lv.${state.level}! 🎉`:`성공! ⭐ +${r.bonus}`;$('visual').textContent='🎉 ⭐ 🎉';$('answers').innerHTML='';$('hintBtn').classList.add('hidden');if(state.gameType==='star-catch'&&state.gameRound<5){$('startBtn').textContent='다음 별 잡기!'}else if(state.gameType==='star-catch'){$('speech').textContent='별잡기 미션 완료!';mood('happy','complete');$('startBtn').textContent='지도로 돌아가기';$('startBtn').dataset.action='map'}else $('startBtn').textContent='한 번 더!';$('startBtn').classList.remove('hidden');updateHud()}
$('startBtn').onclick=()=>$('startBtn').dataset.action==='map'?showMap():next();$('hintBtn').onclick=()=>{state.hints++;mood('hint','hint');const p=state.current;$('speech').textContent='그림으로 천천히 생각해보자!';$('visual').textContent=`${'🔵'.repeat(Math.min(p.a,10))} ${'🟡'.repeat(Math.min(p.b,10))}`;updateHud()};$('treasureBtn').onclick=()=>{if(state.missionStars<MISSION_TARGET)return;state.missionStars-=MISSION_TARGET;state.treasures++;state.stars+=5;state.xp+=20;mood('happy','complete');$('speech').textContent='보물상자 오픈! 보너스 별 5개!';updateHud()};
function showMap(){$('game').classList.add('hidden');$('parentPanel').classList.add('hidden');$('world').classList.remove('hidden');$('worldSuki').src=SUKI_BASE+sukiImages.explore;renderWorld();updateHud()}$('mapBtn').onclick=showMap;$('parentBtn').onclick=()=>{$('world').classList.add('hidden');$('game').classList.add('hidden');$('parentPanel').classList.remove('hidden');updateHud()};$('backBtn').onclick=showMap;
(async()=>{restore();await loadContent();if(!content.worlds.some(w=>w.id===state.currentWorld))state.currentWorld=content.worlds[0]?.id;showMap()})();