const state={stars:0,xp:0,level:1,attempts:0,correct:0,hints:0,round:0,current:null,missionStars:0,treasures:0,gameType:'quiz',gameRound:0};
const $=id=>document.getElementById(id),MISSION_TARGET=20,SUKI_BASE='public/assets/suki/';
const sukiImages={greet:'suki_01_greet.png',happy:'suki_02_happy.png',correct:'suki_03_correct.png',cheer:'suki_04_cheer.png',think:'suki_05_think.png',curious:'suki_06_curious.png',surprise:'suki_07_surprise.png',jump:'avatar_08_jump.png',hint:'suki_09_hint.png',explore:'suki_10_explore.png',rest:'suki_11_rest.png',complete:'suki_12_complete.png'};
const gameNames={quiz:'수키와 대결',catch:'제한시간 별잡기',blank:'빈칸 숫자 찾기',teach:'수키 가르치기'};
function save(){localStorage.setItem('mathPlayState',JSON.stringify(state))}function restore(){try{Object.assign(state,JSON.parse(localStorage.getItem('mathPlayState'))||{})}catch{}}
function setSuki(x='greet'){const i=$('sukiImage'),f=$('sukiFallback');i.onload=()=>{i.hidden=false;f.hidden=true};i.onerror=()=>{i.hidden=true;f.hidden=false};i.src=SUKI_BASE+(sukiImages[x]||sukiImages.greet)}
function mood(m='idle',x='greet'){const a=$('mascot');a.classList.remove('is-happy','is-thinking','is-hint');if(m==='happy')a.classList.add('is-happy');if(m==='thinking')a.classList.add('is-thinking');if(m==='hint')a.classList.add('is-hint');setSuki(x)}
function updateHud(){$('stars').textContent=state.stars;$('level').textContent=`Lv.${state.level}`;$('xpBar').style.width=`${state.xp%100}%`;$('missionStars').textContent=Math.min(state.missionStars,MISSION_TARGET);$('missionBar').style.width=`${Math.min(100,state.missionStars/MISSION_TARGET*100)}%`;$('treasureBtn').classList.toggle('hidden',state.missionStars<MISSION_TARGET);$('attempts').textContent=state.attempts;$('correct').textContent=state.correct;$('hints').textContent=state.hints;const r=state.attempts?Math.round(state.correct/state.attempts*100):0;$('parentSummary').textContent=`오늘 ${state.attempts}번 도전, ${state.correct}번 해결했어요. 성공률 ${r}%, 보물상자 ${state.treasures}개.`;save()}
function problem(){let a=1+Math.floor(Math.random()*6),b=1+Math.floor(Math.random()*(10-a));return{a,b,answer:a+b}}
function choices(ans){const s=new Set([ans]);while(s.size<4)s.add(Math.max(1,Math.min(10,ans-2+Math.floor(Math.random()*5))));return[...s].sort(()=>Math.random()-.5)}
function buttons(items,fn){$('answers').innerHTML='';items.forEach(v=>{let b=document.createElement('button');b.className='answer';b.textContent=v;b.onclick=()=>fn(v);$('answers').appendChild(b)})}
function openGame(type){state.gameType=type;state.gameRound=0;$('world').classList.add('hidden');$('parentPanel').classList.add('hidden');$('game').classList.remove('hidden');$('mode').textContent=gameNames[type];$('speech').textContent=type==='catch'?'5문제를 빠르게 잡아보자!':'준비됐어?';$('visual').textContent='✨';$('question').textContent='';$('answers').innerHTML='';$('startBtn').textContent='게임 시작!';$('startBtn').classList.remove('hidden');$('hintBtn').classList.add('hidden');mood('idle','explore');updateHud()}
function next(){state.current=problem();state.gameRound++;$('startBtn').classList.add('hidden');$('hintBtn').classList.remove('hidden');const p=state.current,m=state.gameType;$('mode').textContent=gameNames[m];
 if(m==='teach'){const wrong=p.answer+(Math.random()<.5?-1:1);$('speech').textContent='수키의 계산을 검사해줘!';$('visual').textContent='🤔';$('question').textContent=`${p.a} + ${p.b} = ${wrong}`;buttons(['맞아','아니야!'],v=>check(v==='아니야!'));mood('thinking','curious');return}
 if(m==='blank'){$('speech').textContent='사라진 숫자를 찾아줘!';$('visual').textContent='🔎✨';$('question').textContent=`${p.a} + □ = ${p.answer}`;buttons(choices(p.b),v=>check(v===p.b));mood('idle','curious');return}
 if(m==='catch'){$('speech').textContent=`별잡기 ${state.gameRound}/5`; $('visual').textContent='⭐💨';$('question').textContent=`${p.a} + ${p.b} = ?`;buttons(choices(p.answer),v=>check(v===p.answer));mood('idle','explore');return}
 $('speech').textContent='수키보다 먼저 정답을 찾아!';$('visual').textContent='⚡ VS ⚡';$('question').textContent=`${p.a} + ${p.b} = ?`;buttons(choices(p.answer),v=>check(v===p.answer));mood('idle','greet')}
function gain(extra=0){const bonus=(state.hints?2:3)+extra;state.stars+=bonus;state.missionStars+=bonus;state.xp+=15+extra*5;let up=false;while(state.xp>=100){state.xp-=100;state.level++;up=true}return{bonus,up}}
function check(ok){state.attempts++;if(!ok){$('speech').textContent='거의 다 왔어! 다시 한번!';mood('thinking','think');updateHud();return}state.correct++;let extra=state.gameType==='teach'?1:0,r=gain(extra);mood('happy',r.up?'jump':state.gameType==='teach'?'cheer':'correct');$('speech').textContent=r.up?`레벨 업! Lv.${state.level}! 🎉`:`성공! ⭐ +${r.bonus}`;$('visual').textContent='🎉 ⭐ 🎉';$('answers').innerHTML='';$('hintBtn').classList.add('hidden');if(state.gameType==='catch'&&state.gameRound<5){$('startBtn').textContent='다음 별 잡기!';$('startBtn').classList.remove('hidden')}else if(state.gameType==='catch'){$('speech').textContent='별잡기 미션 완료!';$('question').textContent='5라운드 끝!';mood('happy','complete');$('startBtn').textContent='지도에서 다른 놀이하기';$('startBtn').classList.remove('hidden');$('startBtn').dataset.action='map'}else{$('startBtn').textContent='한 번 더!';$('startBtn').classList.remove('hidden')}updateHud()}
$('startBtn').onclick=()=>{if($('startBtn').dataset.action==='map'){delete $('startBtn').dataset.action;showMap()}else next()};
$('hintBtn').onclick=()=>{state.hints++;mood('hint','hint');const p=state.current;$('speech').textContent='두 무리를 천천히 세어보자!';$('visual').textContent=`${'🔵'.repeat(p.a)} ${'🟡'.repeat(p.b)}`;updateHud()};
$('treasureBtn').onclick=()=>{if(state.missionStars<MISSION_TARGET)return;state.missionStars-=MISSION_TARGET;state.treasures++;state.stars+=5;state.xp+=20;mood('happy','complete');$('speech').textContent='보물상자 오픈! 보너스 별 5개!';$('visual').textContent='🎁✨ ⭐⭐⭐⭐⭐ ✨🎁';updateHud()};
function showMap(){$('game').classList.add('hidden');$('parentPanel').classList.add('hidden');$('world').classList.remove('hidden');$('worldSuki').src=SUKI_BASE+sukiImages.explore;updateHud()}
document.querySelectorAll('.stage.unlocked').forEach(b=>b.onclick=()=>openGame(b.dataset.game));$('mapBtn').onclick=showMap;$('parentBtn').onclick=()=>{$('world').classList.add('hidden');$('game').classList.add('hidden');$('parentPanel').classList.remove('hidden');updateHud()};$('backBtn').onclick=showMap;restore();updateHud();showMap();